import Head from 'next/head'
import Message from '../components/Message'
import { useEffect,useState, } from 'react'
import { db } from '../utils/firebase'
import { Inter } from '@next/font/google'
import { async } from '@firebase/util'
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //create a state with all the posts
  const [allPosts,setAllPosts] = useState([])
  const getPosts = async()=>{
    const collectionRef = collection(db,'posts')
    const q = query(collectionRef,orderBy('timestamp','desc'))
    const unsubscribe = onSnapshot(q,(snapshot)=>{
      setAllPosts(snapshot.docs.map((doc)=>({...doc.data(),id:doc.id})))
    })
    return unsubscribe
  }
  useEffect(()=>{
    getPosts()
  },[])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='my-12 text-lg font-medium'>
        <h2 className='text-2xl'>See What Other people are saying</h2>
        {allPosts.map((post)=>
          (<Message {...post} key={post.id}>
            <Link href={{pathname:`/${post.id}`,query:{...post}}}>
                <button>{post.comments?.length > 0 ? post.comments : 0}commments</button>
            </Link>
          </Message>)
        )}

      </div>
    </div>
  )
}
